Fired build

diff --git a/.github/workflows/build-push.yml b/.github/workflows/build-push.yml
--- a/.github/workflows/build-push.yml
+++ b/.github/workflows/build-push.yml
@@ -67,41 +67,41 @@ jobs:
 #            az account show
 
 
-      - name: Get GitHub Public IP
-        if: matrix.target.ref == github.ref
-        id: github_public_ip
-        run: echo "ipv4=$(curl 'https://ifconfig.me/ip')" >> $GITHUB_OUTPUT
+#      - name: Get GitHub Public IP
+#        if: matrix.target.ref == github.ref
+#        id: github_public_ip
+#        run: echo "ipv4=$(curl 'https://ifconfig.me/ip')" >> $GITHUB_OUTPUT
+#
+#      - name: Add GitHub IP to ACR
+#        if: matrix.target.ref == github.ref
+#        id: update_firewall
+#        run: az acr network-rule add
+#          --name ${{matrix.target.acr-name}}
+#          --subscription ${{matrix.target.subscription-id}}
+#          --ip-address ${{ steps.github_public_ip.outputs.ipv4 }}
+#
+#      - name: Wait for Specific IP in ACR Network Rules
+#        run: |
+#          MAX_ATTEMPTS=10
+#          ATTEMPT=0
+#          TARGET_IP="${{ steps.github_public_ip.outputs.ipv4 }}"
+#          echo "Waiting for IP $TARGET_IP to be allowed in ACR network rules..."
+#          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
+#            NETWORK_RULES=$(az acr network-rule list --name ${{matrix.target.acr-name}} --subscription ${{ matrix.target.subscription-id }}   --query "ipRules[]|[?contains(ipAddressOrRange, '$TARGET_IP')]"  --output tsv)
+#            if [ -n "$NETWORK_RULES" ]; then
+#              echo "IP $TARGET_IP is now allowed."
+#              break
+#            else
+#              echo "IP $TARGET_IP is not yet allowed. Attempt $((ATTEMPT+1)) of $MAX_ATTEMPTS. Retrying in 10 seconds..."
+#              ATTEMPT=$((ATTEMPT+1))
+#              sleep 5
+#            fi
+#            done
+#            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
+#              echo "IP $TARGET_IP was not allowed after $MAX_ATTEMPTS attempts. Exiting."
+#              exit 1
+#            fi
 
-      - name: Add GitHub IP to ACR
-        if: matrix.target.ref == github.ref
-        id: update_firewall
-        run: az acr network-rule add
-          --name ${{matrix.target.acr-name}}
-          --subscription ${{matrix.target.subscription-id}}
-          --resource-group common
-          --ip-address ${{ steps.github_public_ip.outputs.ipv4 }}
-
-      - name: Wait for Specific IP in ACR Network Rules
-        run: |
-          MAX_ATTEMPTS=10
-          ATTEMPT=0
-          TARGET_IP="${{ steps.github_public_ip.outputs.ipv4 }}"
-          echo "Waiting for IP $TARGET_IP to be allowed in ACR network rules..."
-          while [ $ATTEMPT -lt $MAX_ATTEMPTS ]; do
-            NETWORK_RULES=$(az acr network-rule list --name ${{matrix.target.acr-name}} --subscription ${{ matrix.target.subscription-id }}   --query "ipRules[]|[?contains(ipAddressOrRange, '$TARGET_IP')]"  --output tsv)
-            if [ -n "$NETWORK_RULES" ]; then
-              echo "IP $TARGET_IP is now allowed."
-              break
-            else
-              echo "IP $TARGET_IP is not yet allowed. Attempt $((ATTEMPT+1)) of $MAX_ATTEMPTS. Retrying in 10 seconds..."
-              ATTEMPT=$((ATTEMPT+1))
-              sleep 5
-            fi
-            done
-            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
-              echo "IP $TARGET_IP was not allowed after $MAX_ATTEMPTS attempts. Exiting."
-              exit 1
-            fi
 #      - name: Log in to ACR
 #        run: |
 #          az acr login --name ${{matrix.target.acr-name}}
@@ -121,11 +121,11 @@ jobs:
 #          registry: ${{ matrix.target.acr-name }}.azurecr.io
 #          username: ${{ github.actor }}
 #          password: ${{ secrets.GITHUB_TOKEN }}
-      - name: Get ACR Login Server
-        if: matrix.target.ref == github.ref
-        id: get-acr-login-server
-        run: |
-          echo "login-server=$(az acr show --name ${{ matrix.target.acr-name }} --query loginServer --output tsv)" >> $GITHUB_ENV
+#      - name: Get ACR Login Server
+#        if: matrix.target.ref == github.ref
+#        id: get-acr-login-server
+#        run: |
+#          echo "login-server=$(az acr show --name ${{ matrix.target.acr-name }} --query loginServer --output tsv)" >> $GITHUB_ENV
 
       - name: Get ACR Access Token
         if: matrix.target.ref == github.ref
@@ -136,21 +136,22 @@ jobs:
           echo "::add-mask::$access_token"
           echo "access_token=$access_token" >> $GITHUB_ENV
 
-      - name: Log in to ACR
-        if: matrix.target.ref == github.ref
-        uses: docker/login-action@v3
-        with:
-          registry: ${{ env.login-server }}
-          username: ${{ github.actor }}
-          password: ${{ secrets.GITHUB_TOKEN }}
-#
 #      - name: Log in to ACR
 #        if: matrix.target.ref == github.ref
 #        uses: docker/login-action@v3
 #        with:
 #          registry: ${{ env.login-server }}
-#          username: "00000000-0000-0000-0000-000000000000"
-#          password: ${{ env.access_token }}
+#          username: ${{ github.actor }}
+#          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Log in to ACR
+        if: matrix.target.ref == github.ref
+        uses: docker/login-action@v3
+        with:
+#          registry: ${{ env.login-server }}
+          registry: radixdev.azurecr.io
+          username: "00000000-0000-0000-0000-000000000000"
+          password: ${{ env.access_token }}
 
       - name: Echo environment variable1 for troubleshooting
         run: echo "The image tag is ${{ env.tag }}"
